name: shadowrun_6e_player_helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  shadowrun_6e_player_helper_view_model:
    path: packages/shadowrun_6e_player_helper_view_model
  shadowrun_6e_player_helper_data:
    path: packages/shadowrun_6e_player_helper_data
  flutter:
    sdk: flutter
  theme_tailor_annotation: ^3.1.1
  injectable: ^2.7.0
  get_it: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  theme_tailor: ^3.1.1
  injectable_generator: ^2.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/shadowrun.db
fonts: 
  - family: Ubuntu Sans
    fonts:
      - asset: fonts/Ubuntu-Sans-Regular.ttf
      - asset: fonts/Ubuntu-Sans-Bold.ttf
        weight: 400
      - asset: fonts/Ubuntu-Sans-BoldItalic.ttf
        weight: 400
        style: italic
      - asset: fonts/Ubuntu-Sans-Italic.ttf
        style: italic
      - asset: fonts/Ubuntu-Sans-Medium.ttf
        weight: 200
      - asset: fonts/Ubuntu-Sans-MediumItalic.ttf
        weight: 200
        style: italic